NAME: alertsmodule
BUCKET_NAME: alerts-module
REGION: us-west-2
STAGE: dev
ACCOUNT_ID: 
QUEUE_NAME: alertsQueue

VPC_ID: 
VPC_SG_GROUP_ID: 

VPC_PRIVATE_SUBNET_A:  
VPC_PRIVATE_ROUTE_TABLE_A: 

VPC_PUBLIC_SUBNET_A: 
VPC_PUBLIC_ROUTE_TABLE_A: 

VPC_NAT_GATEWAY_ID: 
VPC_INTERNET_GATEWAY_ID: 

PGHOST: 
PGUSER: 
PGPASSWORD: 
PGDATABASE: 
PGPORT: 5432

TWILIO_ACCOUNT_SID: 
TWILIO_AUTH_TOKEN: 
TWILIO_PHONE_NUMBER: 

SENDGRID_API_KEY: 
SENDGRID_EMAIL_SENDER: 
SENDGRID_TEMPLATE_ID: 
