# docker-compose.yml
version: "3"
services:
  thm_backend:
    container_name: thm_backend
    build: .
    depends_on:
      - thm_database
    environment:
      PG_HOST: thm_database
    volumes:
      - .:/app/
    working_dir: /app
    command: npm run start
    ports:
      - "3000:3000"

  thm_database:
    container_name: thm_database
    image: timescale/timescaledb-postgis:latest-pg12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: concretelife
      POSTGRES_DB: thm_database
    volumes:
      - ./../sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./../sql/insert.sql:/docker-entrypoint-initdb.d/2-insert.sql
      - ./../sql/measures.sql:/docker-entrypoint-initdb.d/3-measures.sql
      - ./../sql/onera.sql:/docker-entrypoint-initdb.d/4-onera.sql